version: "3.7"

services:
  database_sre:
    image: postgres
    container_name: database_solidsre
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=sre
      - POSTGRES_PASSWORD=solid
      - POSTGRES_DB=solid-sre
    volumes:
      - pgdata:/data/postgres
   
volumes:
  pgdata:
    driver: local
